[package]
name = "simple_governance"
version = "0.0.0"

[addresses]
governance = "0x0"
custom_token = "_"
std = "0x1"
aptos_std = "0x1"
aptos_framework = "0x1"

[dependencies.custom_token]
local = "../custom-token"

[dependencies.MoveStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/move-stdlib'

[dependencies.AptosStdlib]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-stdlib'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
